wandb_version: 1

num_samples:
  desc: null
  value: 10000
num_events:
  desc: null
  value: 500000
num_epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747513796.005026
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.2
      8:
      - 5
      - 9
